Fix wheelchairAccessToilet
BISONNL/NeTEx-NL pull request #67
Opened 2024-01-05 14:00 UTC by skinkie

Poging 2.

Align with upstream.

https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_reusableComponents/netex_serviceRestrictions_support.xsd#L684

2024-01-05 14:58 UTC, Joostb61 approved these changes

2024-01-09 10:25 UTC, hilcokats requested changes
Met de wijziging die hier voorligt in de PR verwacht ik niet veel problemen in de praktijk. Ik zou 'm dus kunnen goedkeuren.

Echter, de XSD wordt er wéér eens backwards incompatible door. Dat gebeurt in mijn optiek veel te vaak, namelijk bij vrijwel elke nieuwe versie de laatste tijd, en daar wil ik vanaf, hoe simpel en/of noodzakelijk de wijziging ook is, en hoe acceptabel het ook lijkt. 

Ik snap aan de andere kant ook dat we dit soort wijzigingen moeten doen. In dit geval om in de pas te blijven lopen met Europa. In andere gevallen wellicht om bugs te fixen o.i.d.

Daarom zou ik het volgende willen voorstellen: laten we in dit soort wijzigingen gaan werken met deprecation. Ik realiseer me dat XSD eigenlijk niet zoiets kent. Maar we kunnen binnen Bison best zoiets afspreken, en daar in de documentatie een duidelijke tekst over opnemen, zodat voor iedereen duidelijk is hoe we hiermee omgaan.

Wat mij betreft betekent dit concreet dat we (in dit geval) in de volgende XSD-versie beide varianten van deze enumeratie-waarde opnemen (zowel wheel**C**hairAccessToilet als wheel**c**hairAccessToilet). De oude (met hoofdletter C) markeren we als deprecated in een annotation. Bij deprecated waardes moet altijd het alternatief genoemd worden. Daarnaast kunnen we er ook een datum bij waarop deze naar verwachting verwijderd gaat worden: bijvoorbeeld 1 jaar na (de nog te bepalen) publicatiedatum van deze XSD. 

Als het aan mij ligt gaan we in de toekomst altijd zo om met wijzigingen die de backwards compatibility breken. Je geeft dan alle partijen de tijd om de wijziging te implementen, en geeft meteen een incentive om dit ook daadwerkelijk binnen een jaar te doen.

2024-01-09 14:15 UTC, skinkie commented
> Met de wijziging die hier voorligt in de PR verwacht ik niet veel problemen in de praktijk. Ik zou 'm dus kunnen goedkeuren.
> 
> Echter, de XSD wordt er wéér eens backwards incompatible door. Dat gebeurt in mijn optiek veel te vaak, namelijk bij vrijwel elke nieuwe versie de laatste tijd, en daar wil ik vanaf, hoe simpel en/of noodzakelijk de wijziging ook is, en hoe acceptabel het ook lijkt.

Je moet eerst de uitgangspunten begrijpen voor je het over backwards incompatible hebt. Dit XML Schema is bedoeld om een levering te controleren. Dat betekent per definitie dat iedere fix die in dit schema komt een kwaliteitsverbetering is, ten opzichte van de vorige versie. Dit schema gebruiken om code van te genereren is op ieder moment in de discussie afgeraden.


> Ik snap aan de andere kant ook dat we dit soort wijzigingen moeten doen. In dit geval om in de pas te blijven lopen met Europa. In andere gevallen wellicht om bugs te fixen o.i.d.
> 
> Daarom zou ik het volgende willen voorstellen: laten we in dit soort wijzigingen gaan werken met deprecation. Ik realiseer me dat XSD eigenlijk niet zoiets kent. Maar we kunnen binnen Bison best zoiets afspreken, en daar in de documentatie een duidelijke tekst over opnemen, zodat voor iedereen duidelijk is hoe we hiermee omgaan.

In het geval dat dit schema ongeldig wordt door een wijziging 'upstream' is dat een goede zaak, maar ik zou het veel belangrijker vinden dat er automatisch een volledig schema wordt gegenereerd waar alle elementen uit dit schema in voorkomen (met alle mogelijke waarden) en dat we dat XML-document automatisch tegen het Europese schema valideren. Het gaat nu meerdere keren mis omdat dit schema bewust of onbewust (omdat niemand een element gebruikt) uit de pas loopt.

2024-03-11 12:12 UTC, hilcokats approved these changes

2024-03-11 12:12 UTC, merged